stadsdeel = {'Buurt':'Stadsdeel',
             'Apollobuurt':'Zuid',
             'Banne Buiksloot':'Noord',
             'Bedrijventerrein Sloterdijk':'Westpoort',
             'Betondorp':'Oost',
             'Buiksloterham':'Noord',
             'Buikslotermeer':'Noord',
             'Buitenveldert-Oost':'Zuid',
             'Buitenveldert-West':'Zuid',
             'Burgwallen-Nieuwe Zijde':'Centrum',
             'Burgwallen-Oude Zijde':'Centrum',
             'Centrale Markt':'West',
             'Da Costabuurt':'West',
             'Dapperbuurt':'Oost',
             'De Kolenkit':'West',
             'De Krommert':'West',
             'De Omval':'Oost',
             'De Punt':'Nieuw-West',
             'De Weteringschans':'Centrum',
             'Diamantbuurt':'Zuid',
             'Duivelseiland':'Zuid',
             'Eendracht':'Nieuw-West',
             'Erasmuspark':'West',
             'Frankendael':'Oost',
             'Frederik Hendrikbuurt':'West',
             'Geuzenveld':'Nieuw-West',
             'Grachtengordel-West':'Centrum',
             'Grachtengordel-Zuid':'Centrum',
             'Haarlemmerbuurt':'Centrum',
             'Helmersbuurt':'West',
             'Hoofddorppleinbuurt':'Zuid',
             'Hoofdweg en omgeving':'West',
             'Houthavens':'West',
             'IJburg West':'Oost',
             'IJburg Zuid':'Oost',
             'Ijplein/Vogelbuurt':'Noord',
             'IJselbuurt':'Zuid',
             'Indische Buurt Oost':'Oost',
             'Indische Buurt West':'Oost',
             'Jordaan':'Centrum',
             'Kadoelen':'Noord',
             'Kinkerbuurt':'West',
             'Landlust':'West',
             'Lutkemeer en Ookmeer':'Nieuw-West',
             'Middelveldsche Akerpolder en Sloten':'Osdorp',
             'Middenmeer':'Oost',
             'Museumkwartier':'Zuid',
             'Nieuwe Pijp':'Zuid',
             'Nieuwendammerdijk/Buiksloterdijk':'Noord',
             'Nieuwendammerham':'Noord',
             'Nieuwendam-Noord':'Noord',
             'Nieuwmarkt/Lastage':'Centrum',
             'Oostelijk Havengebied':'Oost',
             'Oostelijke Eilanden/Kadijken':'Centrum',
             'Oosterparkbuurt':'Oost',
             'Oostzanerwerf':'Noord',
             'Osdorp-Midden':'Nieuw-West',
             'Osdorp-Oost':'Nieuw-West',
             'Oude Pijp':'Zuid',
             'Overtoomse Sluis':'West',
             'Overtoomse Veld':'Nieuw-West',
             'Rijnbuurt':'Zuid',
             'Scheldebuurt':'Zuid',
             'Schinkelbuurt':'Zuid',
             'Sloten- en Riekerpolder':'Nieuw-West',
             'Sloterdijk':'Westpoort',
             'Slotermeer-Noordoost':'Nieuw-West',
             'Slotermeer-Zuidwest':'Nieuw-West',
             'Slotervaart':'Nieuw-West',
             'Spaarndammer- en Zeeheldenbuurt':'West',
             'Spieringhorn':'Nieuw-West',
             'Staatsliedenbuurt':'West',
             'Stadionbuurt':'Zuid',
             'Station-Zuid WTC en omgeving':'Zuid',
             'Transvaalbuurt':'Oost',
             'Tuindorp Buiksloot':'Noord',
             'Tuindorp Nieuwendam':'Noord',
             'Tuindorp Oostzaan':'Noord',
             'Van Galenbuurt':'West',
             'Van Lennepbuurt':'West',
             'Volewijck':'Noord',
             'Vondelbuurt':'West',
             'Watergang':'Noord',
             'Waterland':'Noord',
             'Weesperbuurt/Plantage':'Centrum',
             'Weesperzijde':'Oost',
             'Westelijk Havengebied':'Westpoort',
             'Westindische buurt':'Oost',
             'Westlandgracht':'West',
             'Willemspark':'Zuid',
             'Zeeburgereiland/Nieuwe Diep':'Oost'}